apiVersion: v1
kind: Service
metadata:
  name: skadi-backend
  namespace: skadi
  labels:
    app: skadi-backend
spec:
  type: ClusterIP
  selector:
    app: skadi-backend
  ports:
    - name: http
      port: 8080
      targetPort: http
