apiVersion: v1
kind: Service
metadata:
  name: skadi-ia
  namespace: skadi
  labels:
    app: skadi-ia
spec:
  type: ClusterIP
  selector:
    app: skadi-ia
  ports:
    - name: http
      port: 8000
      targetPort: http
