apiVersion: apps/v1
kind: Deployment
metadata:
  name: skadi-redis
  namespace: skadi
  labels:
    app: skadi-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skadi-redis
  template:
    metadata:
      labels:
        app: skadi-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
