apiVersion: v1
kind: Service
metadata:
  name: skadi-redis
  namespace: skadi
  labels:
    app: skadi-redis
spec:
  type: ClusterIP
  selector:
    app: skadi-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
